# Modules
import networkx as nx
import matplotlib.pyplot as plt

# Networkx object
long_room_graph = nx.Graph()

# Waypoints
robotics_lab            = (-0.5,  0.0, "robotics_lab")
matteo_outside          = (3.5,  5.7, "matteo_outside")
mehmet_outside          = (3.5, 11.8, "mehmet_outside")
east_door_east          = (3.2,  3.5, "east_door_east")
east_door_west          = (3.2,  6.0, "east_door_west")
kitchen_inside          = (1.0, 16.2, "kitchen_inside")
kitchen_outside         = (3.3, 15.7, "kitchen_outside")
staff_room_inside_east  = (1.0,  6.0, "staff_room_inside_east")
staff_room_inside_west  = (1.7, 14.2, "staff_room_inside_west")
staff_room_outside_east = (3.0,  6.0, "staff_room_outside_east")
staff_room_outside_west = (3.0, 14.4, "staff_room_outside_west")
staff_room_kitchen_east = (-2.8, 14.5, "staff_room_kitchen_east")
staff_room_kitchen_west = (-3.7, 16.3, "staff_room_kitchen_west")

# Graph's vertices
long_room_graph.add_node(robotics_lab)
long_room_graph.add_node(matteo_outside)
long_room_graph.add_node(mehmet_outside)
long_room_graph.add_node(east_door_east)
long_room_graph.add_node(east_door_west)
long_room_graph.add_node(kitchen_inside)
long_room_graph.add_node(kitchen_outside)
long_room_graph.add_node(staff_room_inside_east)
long_room_graph.add_node(staff_room_inside_west)
long_room_graph.add_node(staff_room_outside_east)
long_room_graph.add_node(staff_room_outside_west)
long_room_graph.add_node(staff_room_kitchen_east)
long_room_graph.add_node(staff_room_kitchen_west)

# Graph's weights
long_room_graph.add_edge(robotics_lab,   east_door_east,   weight = 1)
long_room_graph.add_edge(robotics_lab,   tony_outside,     weight = 1)
long_room_graph.add_edge(east_door_east, tony_outside,     weight = 1)
long_room_graph.add_edge(east_door_east, east_door_west,   weight = 1)
long_room_graph.add_edge(east_door_west, matteo_outside,   weight = 1)
long_room_graph.add_edge(east_door_west, mehmet_outside,   weight = 1)
long_room_graph.add_edge(matteo_outside, mehmet_outside,   weight = 1)
long_room_graph.add_edge(matteo_outside, matteo_inside,    weight = 1)
long_room_graph.add_edge(floor_bump_east, floor_bump_west, weight = 1)
long_room_graph.add_edge(floor_bump_east, east_door_west,  weight = 1)
long_room_graph.add_edge(floor_bump_east, matteo_outside,  weight = 1)
long_room_graph.add_edge(floor_bump_east, mehmet_outside,  weight = 1)
long_room_graph.add_edge(staff_room_outside_east, staff_room_inside_east, weight = 1)
long_room_graph.add_edge(staff_room_outside_east, matteo_outside,  weight = 1)
long_room_graph.add_edge(staff_room_outside_east, mehmet_outside,  weight = 1)
long_room_graph.add_edge(staff_room_outside_east, floor_bump_east, weight = 1)
long_room_graph.add_edge(staff_room_outside_east, east_door_west,  weight = 1)
long_room_graph.add_edge(staff_room_inside_west, staff_room_inside_east, weight = 1)
long_room_graph.add_edge(staff_room_outside_west, staff_room_inside_west, weight = 1)
long_room_graph.add_edge(staff_room_outside_west, floor_bump_east,  weight = 1)
long_room_graph.add_edge(staff_room_outside_west, mehmet_outside,  weight = 1)
long_room_graph.add_edge(staff_room_outside_west, floor_bump_east, weight = 1)
long_room_graph.add_edge(staff_room_outside_west, east_door_west,  weight = 1)
long_room_graph.add_edge(staff_room_inside_west, staff_room_kitchen_east, weight = 1)
long_room_graph.add_edge(staff_room_inside_east, staff_room_kitchen_east,  weight = 1)
long_room_graph.add_edge(staff_room_kitchen_east, staff_room_kitchen_west,  weight = 1)
long_room_graph.add_edge(staff_room_kitchen_west, kitchen_inside, weight = 1)
long_room_graph.add_edge(kitchen_outside, kitchen_inside,  weight = 1)
long_room_graph.add_edge(kitchen_outside, floor_bump_east,  weight = 1)
long_room_graph.add_edge(kitchen_outside, floor_bump_west,  weight = 1)
